[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm run build:content"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/manager"
  to = "/manager.html"
  status = 200
